name: Test Pull Request
on:
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.4

      - name: Test chrome image
        uses: docker/build-push-action@v2.6.1
        with:
          target: test-chrome
          push: false

      - name: Test
        uses: docker/build-push-action@v2.6.1
        with:
          target: test-jupyter
          push: false

      - name: Test image
        uses: docker/build-push-action@v2.6.1
        with:
          target: test-vscode
          push: false
